apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 3
  minReadySeconds: 30
  selector:
    matchLabels:
      app: hello-world-k8s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world-k8s
    spec:
      containers:
      - name: hello-world-k8s
        image: $registry:$BUILD_NUMBER
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name:  hello-world-service
spec:
  selector:
    app:  hello-world-k8s
  type:  NodePort
  ports:
  - name:  http
    port:  8080
    nodePort: 30005
    protocol: TCP
